### ISSUE TITLE
image_index_train_rescaled

### ISSUE THREAD

**Issue by rubenvillegas** [iqbalu/3D_Pose_Estimation_CVPR2016#1]
Hi,

I downloaded the Human3.6m dataset and could not find the "image_index_train_rescaled.txt" file. Can you help me by letting me know where I can get it from?

Regards,
Ruben

**Comment by umariqb** [comment]
Hi Ruben,

Thanks a lot for the notification. The file is not part of Human3.6m datasets, but we created it ourselves.  We will add the file in the code soon. Meanwhile, I am copying it here. 
[image_index_train_rescaled.txt](https://github.com/iqbalu/3D_Pose_Estimation_CVPR2016/files/478339/image_index_train_rescaled.txt)

Feel free to contact if you find any other problem. 

BR,
Umar

**Comment by rubenvillegas** [comment]
Thank you very much for the fast response

**Comment by rubenvillegas** [comment]
In the file, I see a bunch of paths to images like this "Human36M/images_rescaled/Directions1_S1_C2_145.png". Is there a script to create these type of files in this repo? Or am I missing something?

Thanks,
Ruben

**Comment by umariqb** [comment]
The image files are required only if you want to retrain 2D pose estimators. Otherwise, you only need the pose coordinates given in the file.

**Comment by rubenvillegas** [comment]
When I run "RUN_Iterated.m", I get this error:

I0917 16:10:02.001082 15584 eval_pose_human36m_multiscale.cpp:144] file_name: /home/3D_Pose_Estimation_CVPR2016/temp/PE_Data2/estimatedPose_human36m_multiscale_6s.txt

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
terminate called after throwing an instance of 'cv::Exception'
  what():  /tmp/B3p0_293380_4550/build-glnxa64.glnxa64.293380.r000/B3p0/glnxa64/OpenCV/modules/imgproc/src/imgwarp.cpp:1834: error: (-215) ssize.area() > 0 in function resize

../MEX/src/eval_pose_human36m_multiscale/eval_pose_human36m_multiscale regress_02 30 /home/3D_Pose_Estimation_CVPR2016/MEX/src/regressors /home/3D_Pose_Estimation_CVPR2016/temp/PE_Data2/tmp_annotation.txt /home/datasets/Human3.6M/image_index_train_rescaled.txt /home/3D_Pose_Estimation_CVPR2016/temp/PE_Data2/ estimatedPose_human36m_multiscale_6s.txt: Aborted

Elapsed time is 47.146304 seconds.
    Done
Starting round 1
Struct contents reference from a non-struct array object.

Error in H_text2MotFileUmH36Mbm (line 14)
motIn.nframes    = size(impData.data,1);

Error in H_dirFilesUm (line 93)
              returnFileName = H_text2MotFileUmH36Mbm(inputFileName, strPath, savePath);

Error in RUN_Iterated (line 76)
            tmp_convertedFile = [opts.loadInPath H_dirFilesUm('Human36Mbm', ...

I think maybe the code is trying to load these files. Not sure though. If so, is there a ways to deactivate training and just test?

**Comment by umariqb** [comment]
It seems that the code is not able to find the image. Some CV::Mat variable has size zero "ssize.area() > 0 in function resize"
@anDoer can you please check what is the issue. Thanks!

**Comment by umariqb** [comment]
@rubenvillegas  I am trying to reproduce the problem. Let me check if I can do something quickly. Otherwise, we should be able to fix the problem next week.

**Comment by rubenvillegas** [comment]
@iqbalu Ok. Thank you!

**Comment by umariqb** [comment]
@rubenvillegas  have you changed the following variable in Initialize.m?

TDPose_TestImageLocation = /media/data/doering/cluster_3DPose/3D_Pose_Estimation_Public_v1/S11_im';

**Comment by rubenvillegas** [comment]
@iqbalu Yes. I did change that variable

**Comment by umariqb** [comment]
@rubenvillegas  I have pushed some changes in MEX/src directory. Actually, I have added assertions to assure that the image is loaded properly. At the moment it seems to be a path issue i.e., code is not able to find images for you. Just pull the latest code and paste the error here. Thanks!
