### ISSUE TITLE
Reduce ram requirement

### ISSUE THREAD

**Issue by hetpin** [iqbalu/3D_Pose_Estimation_CVPR2016#2]
Hi, I'm very interested in your work of 3D human pose estimation. Just try to run your source, but my ram is not enough. Can you show me how to change/reduce the ram requirement to run this source. 

I though 32G ram is used to load db.mat(~13G) into memory, then could you share a smaller normalized dataset.

Looking forward to hearing from you.
Best,
-Thanh

**Comment by umariqb** [comment]
Hello Hetpin,

Actually, you can yourself reduce the size of the database. If you load db.mat, you will find 3D poses and their corresponding 2D projections. You can select a lesser number of 3D poses, and only keep the required projections.

Hope that helps!
Umar
